exts_n_paths = [
	'.txt', 'C:/windows/system32/notepad.exe',
	'.v', 'C:/Users/PACHECON/Apps/vscodium/VSCodium.exe',
	'.py', 'C:/Users/PACHECON/Apps/vscodium/VSCodium.exe',
	'', 'C:/windows/system32/notepad.exe',
	'.exe', 'start ',
	'else', 'C:/windows/system32/notepad.exe',
]


bg_color = [20, 10, 10]
folder_highlight = [163, 81, 181]
choice_highlight = [63, 81, 181]